---
spring:
  application:
    name: app-one
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: local

logging:
  level:
    org.springframework.security: DEBUG

named-environment:
  raft:
    val1: raft_local_val1
    val2: raft_local_val2
  ecif:
    val1: ecif_local_val1
    val2: ecif_local_val2

---
spring:
  profiles: local
---
spring:
  profiles: unittest
---
spring:
  profiles: cloud-dev1
---
spring:
  profiles: cloud-qa1
---
spring:
  profiles: cloud-stage1
---
spring:
  profiles: prod
  
