---
spring:
  profiles:
    active: cloud-qa1

logging:
  level:
    org.springframework.security: INFO

named-environment:
  cloud-qa1:
    raft:
      val1: raft_val1-qa1
      val2: raft_val2-qa1
    ecif:
      val1: ecif_val1
      val2: ecif_val2