---
spring:
  application:
    name: app-one
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: local

logging:
  level:
    org.springframework.security: DEBUG

named-environment:
  local:
    raft:
      val1: raft_val1-local
      val2: raft_val2-local
    ecif:
      val1: ecif_val1
      val2: ecif_val2

---
spring:
  profiles: local
---
spring:
  profiles: unittest
---
spring:
  profiles: cloud-dev1
---
spring:
  profiles: cloud-qa1
---
spring:
  profiles: cloud-stage1
---
spring:
  profiles: prod
  
