---
spring:
  profiles:
    active: cloud-dev1

logging:
  level:
    org.springframework.security: INFO

named-environment:
  raft:
    val1: raft_dev1_val1
    val2: raft_dev1_val2
  ecif:
    val1: ecif_dev1_val1
    val2: ecif_dev1_val2
  