---
spring:
  profiles:
    active: cloud-qa1

logging:
  level:
    org.springframework.security: INFO

named-environment:
  raft:
    val1: raft_qa1_val1
    val2: raft_qa1_val2
  ecif:
    val1: ecif_qa1_val1
    val2: ecif_qa1_val2