---
spring:
  profiles:
    active: cloud-dev1

logging:
  level:
    org.springframework.security: INFO

named-environment:
  cloud-dev1:
    raft:
      val1: raft_val1-dev1
      val2: raft_val2-dev1
    ecif:
      val1: ecif_val1
      val2: ecif_val2
  